#!/usr/bin/env bash
set -euo pipefail

COOKIE_JAR=$(mktemp)
trap "rm -f $COOKIE_JAR" EXIT

LIGHTDASH_URL="http://localhost:8080"
ADMIN_EMAIL="admin@example.com"
ADMIN_PASSWORD="Password1!"

echo "==> コンテナ起動"
docker compose up -d

echo "==> Lightdash の起動を待機中..."
until curl -sf "$LIGHTDASH_URL/api/v1/health" > /dev/null 2>&1; do
  sleep 2
done
echo "==> Lightdash 起動完了"

# 初期セットアップが必要か確認
NEEDS_SETUP=$(curl -s "$LIGHTDASH_URL/api/v1/health" | python3 -c "import sys,json; print(json.load(sys.stdin)['results']['requiresOrgRegistration'])")

if [ "$NEEDS_SETUP" = "True" ]; then
  echo "==> 初期ユーザー登録"
  curl -s -X POST "$LIGHTDASH_URL/api/v1/user" \
    -H "Content-Type: application/json" \
    -d "{\"firstName\":\"Admin\",\"lastName\":\"User\",\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}" > /dev/null

  echo "==> 組織作成"
  curl -s -c "$COOKIE_JAR" -X POST "$LIGHTDASH_URL/api/v1/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}" > /dev/null

  curl -s -b "$COOKIE_JAR" -X PUT "$LIGHTDASH_URL/api/v1/org" \
    -H "Content-Type: application/json" \
    -d '{"name":"Sandbox"}' > /dev/null

  # org作成後に再ログイン
  curl -s -c "$COOKIE_JAR" -X POST "$LIGHTDASH_URL/api/v1/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}" > /dev/null

  curl -s -b "$COOKIE_JAR" -X PATCH "$LIGHTDASH_URL/api/v1/user/me/complete" \
    -H "Content-Type: application/json" \
    -d '{}' > /dev/null

  echo "==> プロジェクト作成"
  PROJECT_UUID=$(curl -s -b "$COOKIE_JAR" -X POST "$LIGHTDASH_URL/api/v1/org/projects" \
    -H "Content-Type: application/json" \
    -d '{
      "name": "Sandbox",
      "type": "DEFAULT",
      "dbtConnection": { "type": "none" },
      "dbtVersion": "v1.11",
      "warehouseConnection": {
        "type": "postgres",
        "host": "db",
        "port": 5432,
        "user": "lightdash",
        "password": "lightdash_password",
        "dbname": "lightdash",
        "schema": "public",
        "sslmode": "disable"
      }
    }' | python3 -c "import sys,json; print(json.load(sys.stdin)['results']['project']['projectUuid'])")

  echo "==> PAT 作成"
  TOKEN=$(curl -s -b "$COOKIE_JAR" -X POST "$LIGHTDASH_URL/api/v1/user/me/personal-access-tokens" \
    -H "Content-Type: application/json" \
    -d '{"description":"setup","expiresAt":null,"autoGenerated":false}' \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['results']['token'])")

  echo "==> dbt seed & run"
  uv run dbt seed --profiles-dir .
  uv run dbt run --profiles-dir .

  echo "==> Lightdash へデプロイ"
  PATH="$PWD/.venv/bin:$PATH" \
  LIGHTDASH_API_KEY="$TOKEN" \
  LIGHTDASH_URL="$LIGHTDASH_URL" \
  LIGHTDASH_PROJECT="$PROJECT_UUID" \
  npx --yes @lightdash/cli deploy --profiles-dir . --project-dir .

  echo "==> チャート・ダッシュボードをアップロード"
  PATH="$PWD/.venv/bin:$PATH" \
  LIGHTDASH_API_KEY="$TOKEN" \
  LIGHTDASH_URL="$LIGHTDASH_URL" \
  LIGHTDASH_PROJECT="$PROJECT_UUID" \
  npx --yes @lightdash/cli upload --path lightdash --force --public --include-charts

  echo "==> 初期セットアップ完了"
else
  echo "==> セットアップ済み、dbt のみ実行"
  uv run dbt seed --profiles-dir .
  uv run dbt run --profiles-dir .
fi

echo ""
echo "=============================="
echo "セットアップ完了!"
echo "  URL:      $LIGHTDASH_URL"
echo "  Email:    $ADMIN_EMAIL"
echo "  Password: $ADMIN_PASSWORD"
echo "=============================="
